### PR TITLE
Correction of 16 pony images

### PR DESCRIPTION
**Pull request by maandree**
16 Pinkie Pie images were corrupt and not readable some programs, including web browsers.
All other images appear to be correct.

### CODE REVIEW

**Comment by panzi** [comment]
I can't see any difference between the images. In what browser do they look corrupted? They look fine to me in Chrome 19, Firefox 13 and Opera 12 (didn't want to boot Windows to test IE). How did you fix the images?

**Comment by maandree** [comment]
The images look identical, but I fixed them by re-saving them using GIMP.

ImageMagick was unable to read it, and I've have experienced this kind of problem
also being a problem for some (less well known) browser, however that didn't seem
to be the case with any I currently have installed, but no doubt if at least on program
have a problem, others will to.

I noticed however that NetSurf do not support browser-ponies, there may be some more,
I only have few browsers installed at this times.

**Comment by panzi** [comment]
I only test with the newest Firefox, Chrome, Opera and occasionally IE8 and IE9. IE<=8 has no transparent iframes so the effects (sonic rainboom etc.) look wrong there anyway.

However, did you look at the original files from http://www.desktopponies.com/? Are they also corrupted? Then please tell them. I only take their resources. If they have corrupted files even if I now pull your fixes next time there is an update I will have the corrupted files again.

**Comment by maandree** [comment]
Theirs was also corrupt, I will report it to them.

**Pull request merged**
